name: build-publish-all
run-name: Build and publish artifacts
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build_appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker builder
        run: docker build -t samrewritten-builder -f package/appimage.Dockerfile .

      - name: Build GTK AppImage version
        run: docker run --rm -v ./:/mnt:z samrewritten-builder sh -c "cargo appimage"

      - name: Add permissions
        run: sudo chmod 777 target/appimage

      - name: Rename GTK AppImage
        run: mv target/appimage/samrewritten.AppImage target/appimage/samrewritten-gtk.AppImage

      - name: Build Adwaita AppImage version
        run: docker run --rm -v ./:/mnt:z samrewritten-builder sh -c "cargo appimage --features adwaita"

      - name: Rename Adwaita AppImage
        run: mv target/appimage/samrewritten.AppImage target/appimage/samrewritten-adw.AppImage

      - name: Build CLI AppImage version
        run: docker run --rm -v ./:/mnt:z samrewritten-builder sh -c "cargo appimage --features cli"

      - name: Rename CLI AppImage
        run: mv target/appimage/samrewritten.AppImage target/appimage/samrewritten-cli.AppImage

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: target/appimage
          retention-days: 1

  create_release:
    runs-on: ubuntu-latest
    needs: [ build_appimage ] # This job depends on both build jobs
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-artifact
          path: ./release_artifacts/linux

      - name: List artifacts
        run: |
          ls -la ./release_artifacts
          ls -la ./release_artifacts/linux

      - name: Create Release
        id: create_release # Assign an ID to this step to access its outputs
        uses: softprops/action-gh-release@v2
        with:
          # The tag name for the release. github.ref_name automatically extracts the tag name (e.g., v1.0.0 from refs/tags/v1.0.0)
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # The release body (notes). You can specify a string or use a file (body_path).
          # For auto-generating release notes based on PRs, you might use other actions like 'release-drafter'.
          body: |
            ## Release Notes for ${{ github.ref_name }}

            This release includes:
            - Latest features and bug fixes.
            - Built on ${{ github.sha }}

          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            release_artifacts/linux/samrewritten-gtk.AppImage
            release_artifacts/linux/samrewritten-adw.AppImage
            release_artifacts/linux/samrewritten-cli.AppImage